server:
  port: 9131

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_manager?useUnicode=true&characterEncoding=utf-8&serveTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

Logging:
  level:
    com.rabbiter: debug